/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputSize } from "./components/validated-input/validated-input.component";
export namespace Components {
    interface ValidatedInput {
        "placeholder": string;
        "size": InputSize;
        "type": string;
        "validationPattern": string;
    }
}
declare global {
    interface HTMLValidatedInputElement extends Components.ValidatedInput, HTMLStencilElement {
    }
    var HTMLValidatedInputElement: {
        prototype: HTMLValidatedInputElement;
        new (): HTMLValidatedInputElement;
    };
    interface HTMLElementTagNameMap {
        "validated-input": HTMLValidatedInputElement;
    }
}
declare namespace LocalJSX {
    interface ValidatedInput {
        "onUserInputChanged"?: (event: CustomEvent<string>) => void;
        "onValidationChanged"?: (event: CustomEvent<boolean>) => void;
        "placeholder"?: string;
        "size"?: InputSize;
        "type"?: string;
        "validationPattern"?: string;
    }
    interface IntrinsicElements {
        "validated-input": ValidatedInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "validated-input": LocalJSX.ValidatedInput & JSXBase.HTMLAttributes<HTMLValidatedInputElement>;
        }
    }
}
